FROM postgres:10

ENV POSTGRES_USER=catalog_user \
    POSTGRES_PASSWORD=catalog_passwd \
    POSTGRES_DB=catalog_db_name

RUN apt-get -y update; apt-get -y install curl

COPY ./docker/context/catalog/init-catalog.sh /docker-entrypoint-initdb.d/init-catalog.sh

COPY ./scripts/fetch_landsat_data.sh /scripts/fetch_landsat_data.sh
EXPOSE 5432

ENTRYPOINT ["/bin/bash", "/scripts/fetch_landsat_data.sh"
