FROM node:12-alpine

WORKDIR /dashboard
COPY package*.json ./
RUN npm install

COPY . .
RUN apk update && apk add jq && \
    apk add nginx && apk add gawk && \
    npm install pm2 -g

COPY ./nginx/default /etc/nginx/sites-available/default
COPY ./docker/entrypoint.sh /
RUN apk add --no-cache bash

EXPOSE 80

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
