FROM maven:3.6.0-jdk-8-alpine AS builder

WORKDIR app
RUN apk update && apk add git && \
    git clone https://github.com/ufcg-lsd/saps-common && \
    cd saps-common && mvn install && \
    git clone https://github.com/ufcg-lsd/saps-catalog && \
    cd saps-catalog && mvn install

COPY pom.xml .
COPY src  ./src
RUN mvn install

FROM openjdk:8-alpine
COPY --from=builder /app/target/saps-dispatcher-0.0.1-SNAPSHOT.jar dispatcher.jar
COPY --from=builder /app/target/lib lib/
COPY ./resources resources/
COPY ./config/dispatcher.conf config/dispatcher.conf
COPY ./config/log4j.properties config/log4j.properties

ENTRYPOINT java -Dlog4j.configuration=file:./config/log4j.properties -Djava.library.path=/usr/local/lib -cp dispatcher.jar:lib/*  saps.dispatcher.core.SubmissionDispatcherMain ./config/dispatcher.conf ./resources/execution_script_tags.json
