FROM postgres:12

ENV POSTGRES_USER=catalog_user \
    POSTGRES_PASSWORD=catalog_passwd \
    POSTGRES_DB=catalog_db_name

RUN apt-get -y update; apt-get -y install curl

COPY ./docker/context/catalog/init-catalog.sh /docker-entrypoint-initdb.d/init-catalog.sh

EXPOSE 5432
