FROM maven:3.6.0-jdk-8-alpine AS builder

WORKDIR /app
RUN apk update && apk add git && \
    git clone https://github.com/ufcg-lsd/saps-common && \
    cd saps-common && mvn install && \
    git clone https://github.com/ufcg-lsd/saps-catalog && \
    cd saps-catalog && mvn install

COPY pom.xml .
COPY src  ./src
RUN mvn install

FROM openjdk:8-alpine
ENV MAIN_CLASS="saps.scheduler.core.SchedulerMain" \
    SERVICE_CONF_PATH="./config/scheduler.conf" \
    LOG_PROPERTIES_PATH="./config/log4j.properties"

WORKDIR /scheduler

COPY --from=builder /app/target/saps-scheduler-0.0.1-SNAPSHOT.jar scheduler.jar
COPY --from=builder /app/target/lib lib/
COPY ./config/scheduler.conf config/scheduler.conf
COPY ./config/log4j.properties config/log4j.properties
COPY ./resources resources/

ENTRYPOINT java -Dlog4j.configuration=file:"${LOG_PROPERTIES_PATH}" -cp scheduler.jar:lib/* "${MAIN_CLASS}" "${SERVICE_CONF_PATH}"


