FROM postgres:12

FROM maven:3.6.3-jdk-8 AS builder

EXPOSE 5433

WORKDIR app

COPY pom.xml .
COPY src  ./src
RUN mvn install

FROM openjdk:8-alpine

WORKDIR service

COPY --from=builder /app/bin/arrebol-service-1.0.jar  arrebol.jar
COPY --from=builder /app/bin/lib lib/
COPY ./src/main/resources/arrebol.json ./config/arrebol.json

ENTRYPOINT ["java", "-jar", "arrebol.jar", "-c" , "./config/arrebol.json"]
